### ISSUE TITLE
Enhancement - typo fix

### ISSUE THREAD

**Issue by raystep-code** [jasoncdavis/SSH2Influx#1]
in Readme.md, look for "suite" and replace with "suit"
i.e. it suits you, not suites you

**Comment by jasoncdavis** [comment]
I merged the fix with the enhanced threadpool feature.
Thanks for the catch, Ray!

How suite it is to know others care...   :)

**Comment by raystep-code** [comment]
I see what you did there. It is a suite life.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
